on: push

name: Build. Publish on merge

jobs:
  build:
    name: Docker build${{ (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && ' and push') || '' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build${{ (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && ' and push') || '' }} Docker images
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        # Only push on default branch.
        push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        context: .
        platforms: linux/amd64,linux/arm64
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ghcr.io/${{ github.repository }}:latest
