name: Lint
on: pull_request

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run hadolint
      uses: hadolint/hadolint-action@v3.1.0
